# import Data

In [105]:
import numpy as np
import kagglehub
import pandas as pd
import os

import plotly.graph_objects as go
from sklearn.preprocessing import MinMaxScaler

from keras.layers import Dense, Flatten, LSTM, Dropout
from keras.models import Sequential
from keras.layers import SpatialDropout1D
from tensorflow.keras import activations

from sklearn.metrics import mean_squared_error

In [106]:
path = kagglehub.dataset_download("nitirajkulkarni/bangkok-th-1609350")
print("Path to dataset files:", path)

Using Colab cache for faster access to the 'bangkok-th-1609350' dataset.
Path to dataset files: /kaggle/input/bangkok-th-1609350

In [107]:
file_path = os.path.join(path, "air_quality_historical.csv")
df = pd.read_csv(file_path)
df.head()

,date,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,aerosol_optical_depth,dust,uv_index,us_aqi,european_aqi
0,2022-08-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-08-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022-08-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022-08-04,18.758824,12.876471,328.058824,17.723529,8.682353,44.235294,0.125882,0.0,1.697059,NaN,NaN
4,2022-08-05,16.229167,11.100000,256.250000,13.625000,6.650000,37.208333,0.135833,0.0,0.916667,46.117647,23.117647

# Prepare training data

In [108]:
df['date'] = pd.to_datetime(df['date'])
df_2025 = df[(df['date'].dt.year == 2025) & (df['date'].dt.month > 8)]
df = df_2025
df.head()

,date,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,aerosol_optical_depth,dust,uv_index,us_aqi,european_aqi
1127,2025-09-01,9.379167,8.845833,1295.125000,16.395833,8.195833,48.458333,0.147917,0.000000,2.218750,32.875000,22.916667
1128,2025-09-02,11.229167,10.612500,1565.583333,18.912500,10.170833,46.666667,0.163750,0.333333,1.252083,42.333333,24.250000
1129,2025-09-03,14.016667,11.958333,969.083333,20.279167,9.804167,48.500000,0.204583,2.041667,2.389583,41.583333,26.916667
1130,2025-09-04,18.016667,14.687500,1177.750000,22.454167,10.729167,48.083333,0.267917,4.416667,1.620833,55.916667,31.333333
1131,2025-09-05,17.700000,15.191667,947.583333,21.129167,12.387500,50.875000,0.290417,3.708333,2.122917,56.333333,34.041667

In [109]:
fig_pm2_5 = go.Figure()
fig_pm2_5.add_trace(go.Scatter(x=df['date'], y=df['pm2_5'], mode='lines', name='PM2.5 Actual'))
fig_pm2_5.update_layout(title='PM2.5 Values Over Time (2025)', xaxis_title='Date', yaxis_title='PM2.5 Value')
fig_pm2_5.show()

In [110]:
X=np.array(df['pm2_5'])

In [111]:
scaler = MinMaxScaler(feature_range=(0, 1))
X_normalized = scaler.fit_transform(np.array([X]).T)

In [112]:
X_train=X_normalized[:-1]
Y_train=X_normalized[1:]

In [113]:
lag = 3

In [114]:
ind=np.arange(lag)
ind=np.arange(X.shape[0]-lag).reshape(X.shape[0]-lag,1)+ind
X_train=X_normalized[ind]
X_train=X_train.reshape((X_train.shape[0],1,X_train.shape[1]))

In [115]:
X_train.shape

(119, 1, 3)

In [116]:
X_train

array([[[0.10357174, 0.14059907, 0.16880622]],

       [[0.14059907, 0.16880622, 0.22600646]],

       [[0.16880622, 0.22600646, 0.23657323]],

       [[0.22600646, 0.23657323, 0.28320671]],

       [[0.23657323, 0.28320671, 0.17622915]],

       [[0.28320671, 0.17622915, 0.03274823]],

       [[0.17622915, 0.03274823, 0.05466771]],

       [[0.03274823, 0.05466771, 0.04008384]],

       [[0.05466771, 0.04008384, 0.09562484]],

       [[0.04008384, 0.09562484, 0.47960877]],

       [[0.09562484, 0.47960877, 0.51305563]],

       [[0.47960877, 0.51305563, 0.30530085]],

       [[0.51305563, 0.30530085, 0.15727884]],

       [[0.30530085, 0.15727884, 0.18260414]],

       [[0.15727884, 0.18260414, 0.13981312]],

       [[0.18260414, 0.13981312, 0.12147411]],

       [[0.13981312, 0.12147411, 0.03947254]],

       [[0.12147411, 0.03947254, 0.        ]],

       [[0.03947254, 0.        , 0.11544843]],

       [[0.        , 0.11544843, 0.26076325]],

       [[0.11544843, 0.26076325, 0.0573749 ]],

       [[0.26076325, 0.0573749 , 0.00847088]],

       [[0.0573749 , 0.00847088, 0.03091433]],

       [[0.00847088, 0.03091433, 0.07807178]],

       [[0.03091433, 0.07807178, 0.17422059]],

       [[0.07807178, 0.17422059, 0.2136058 ]],

       [[0.17422059, 0.2136058 , 0.10156318]],

       [[0.2136058 , 0.10156318, 0.00925683]],

       [[0.10156318, 0.00925683, 0.09815737]],

       [[0.00925683, 0.09815737, 0.59269933]],

       [[0.09815737, 0.59269933, 0.60064623]],

       [[0.59269933, 0.60064623, 0.14086106]],

       [[0.60064623, 0.14086106, 0.14112305]],

       [[0.14086106, 0.14112305, 0.19142433]],

       [[0.14112305, 0.19142433, 0.2377085 ]],

       [[0.19142433, 0.2377085 , 0.17404593]],

       [[0.2377085 , 0.17404593, 0.37813291]],

       [[0.17404593, 0.37813291, 0.63418042]],

       [[0.37813291, 0.63418042, 0.4870317 ]],

       [[0.63418042, 0.4870317 , 0.56833464]],

       [[0.4870317 , 0.56833464, 0.59776439]],

       [[0.56833464, 0.59776439, 0.42529037]],

       [[0.59776439, 0.42529037, 0.35289494]],

       [[0.42529037, 0.35289494, 0.68299712]],

       [[0.35289494, 0.68299712, 0.3759497 ]],

       [[0.68299712, 0.3759497 , 0.43812767]],

       [[0.3759497 , 0.43812767, 0.50877653]],

       [[0.43812767, 0.50877653, 0.37463977]],

       [[0.50877653, 0.37463977, 0.52615492]],

       [[0.37463977, 0.52615492, 0.56064972]],

       [[0.52615492, 0.56064972, 0.35830932]],

       [[0.56064972, 0.35830932, 0.45952319]],

       [[0.35830932, 0.45952319, 0.4363811 ]],

       [[0.45952319, 0.4363811 , 0.4574273 ]],

       [[0.4363811 , 0.4574273 , 0.5327919 ]],

       [[0.4574273 , 0.5327919 , 0.58221989]],

       [[0.5327919 , 0.58221989, 0.5709545 ]],

       [[0.58221989, 0.5709545 , 0.54353332]],

       [[0.5709545 , 0.54353332, 0.46546153]],

       [[0.54353332, 0.46546153, 0.2087154 ]],

       [[0.46546153, 0.2087154 , 0.18924111]],

       [[0.2087154 , 0.18924111, 0.48257794]],

       [[0.18924111, 0.48257794, 0.64518383]],

       [[0.48257794, 0.64518383, 0.6802026 ]],

       [[0.64518383, 0.6802026 , 0.81695922]],

       [[0.6802026 , 0.81695922, 0.64352458]],

       [[0.81695922, 0.64352458, 0.38948563]],

       [[0.64352458, 0.38948563, 0.52248712]],

       [[0.38948563, 0.52248712, 0.46441359]],

       [[0.52248712, 0.46441359, 0.81818182]],

       [[0.46441359, 0.81818182, 0.71757925]],

       [[0.81818182, 0.71757925, 0.49951969]],

       [[0.71757925, 0.49951969, 0.41114313]],

       [[0.49951969, 0.41114313, 0.36232643]],

       [[0.41114313, 0.36232643, 0.4104445 ]],

       [[0.36232643, 0.4104445 , 0.32861759]],

       [[0.4104445 , 0.32861759, 0.25089512]],

       [[0.32861759, 0.25089512, 0.25185573]],

       [[0.25089512, 0.25185573, 0.27534713]],

       [[0.25185573, 0.27534713, 0.42616365]],

       [[0.27534713, 0.42616365, 0.43297529]],

       [[0.42616365, 0.43297529, 0.50982447]],

       [[0.43297529, 0.50982447, 0.43996158]],

       [[0.50982447, 0.43996158, 0.50606934]],

       [[0.43996158, 0.50606934, 0.59051611]],

       [[0.50606934, 0.59051611, 0.4574273 ]],

       [[0.59051611, 0.4574273 , 0.52493232]],

       [[0.4574273 , 0.52493232, 0.55244083]],

       [[0.52493232, 0.55244083, 0.72823334]],

       [[0.55244083, 0.72823334, 0.84726225]],

       [[0.72823334, 0.84726225, 0.74107065]],

       [[0.84726225, 0.74107065, 0.73032923]],

       [[0.74107065, 0.73032923, 0.32119466]],

       [[0.73032923, 0.32119466, 0.36695485]],

       [[0.32119466, 0.36695485, 0.61811196]],

       [[0.36695485, 0.61811196, 0.58248188]],

       [[0.61811196, 0.58248188, 0.35280762]],

       [[0.58248188, 0.35280762, 0.42511571]],

       [[0.35280762, 0.42511571, 0.52205048]],

       [[0.42511571, 0.52205048, 0.42153524]],

       [[0.52205048, 0.42153524, 0.45410881]],

       [[0.42153524, 0.45410881, 0.48930224]],

       [[0.45410881, 0.48930224, 0.41620819]],

       [[0.48930224, 0.41620819, 0.39516199]],

       [[0.41620819, 0.39516199, 0.58300585]],

       [[0.39516199, 0.58300585, 0.42991878]],

       [[0.58300585, 0.42991878, 0.4055541 ]],

       [[0.42991878, 0.4055541 , 0.64710506]],

       [[0.4055541 , 0.64710506, 0.82499345]],

       [[0.64710506, 0.82499345, 0.49227142]],

       [[0.82499345, 0.49227142, 0.5190813 ]],

       [[0.49227142, 0.5190813 , 0.8159986 ]],

       [[0.5190813 , 0.8159986 , 0.92446075]],

       [[0.8159986 , 0.92446075, 0.629552  ]],

       [[0.92446075, 0.629552  , 0.32067068]],

       [[0.629552  , 0.32067068, 0.29281285]],

       [[0.32067068, 0.29281285, 0.44144616]],

       [[0.29281285, 0.44144616, 0.53060868]],

       [[0.44144616, 0.53060868, 0.86673653]]])

In [117]:
Y_train=X_train[:,:,0][1:,:]
X_train=X_train[:-1,:,:]

# Train Model using LSTM

In [118]:
model = Sequential()
model.add(LSTM(16, input_shape=(1, lag)))
model.add(Dense(4))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.

In [119]:
epochs = 100
batch_size = 5

history = model.fit(X_train, Y_train, epochs=epochs, batch_size=batch_size,validation_split=0.1)

Epoch 1/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - loss: 0.1575 - val_loss: 0.1973
Epoch 2/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0625 - val_loss: 0.0770
Epoch 3/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0288 - val_loss: 0.0356
Epoch 4/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0225 - val_loss: 0.0301
Epoch 5/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0205 - val_loss: 0.0246
Epoch 6/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0184 - val_loss: 0.0246
Epoch 7/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0161 - val_loss: 0.0205
Epoch 8/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0139 - val_loss: 0.0179
Epoch 9/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0121 - val_loss: 0.0150
Epoch 10/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0102 - val_loss: 0.0136
Epoch 11/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0086 - val_loss: 0.0103
Epoch 12/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0074 - val_loss: 0.0085
Epoch 13/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0061 - val_loss: 0.0072
Epoch 14/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0051 - val_loss: 0.0062
Epoch 15/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0044 - val_loss: 0.0051
Epoch 16/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0039 - val_loss: 0.0045
Epoch 17/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0034 - val_loss: 0.0038
Epoch 18/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0031 - val_loss: 0.0035
Epoch 19/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0027 - val_loss: 0.0031
Epoch 20/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0025 - val_loss: 0.0026
Epoch 21/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0022 - val_loss: 0.0024
Epoch 22/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0020 - val_loss: 0.0022
Epoch 23/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0019 - val_loss: 0.0019
Epoch 24/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0016 - val_loss: 0.0015
Epoch 25/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0015 - val_loss: 0.0013
Epoch 26/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - val_loss: 0.0012
Epoch 27/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0011 - val_loss: 0.0012
Epoch 28/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0010 - val_loss: 9.2054e-04
Epoch 29/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.4923e-04 - val_loss: 6.9216e-04
Epoch 30/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.5097e-04 - val_loss: 6.2779e-04
Epoch 31/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 6.6001e-04 - val_loss: 3.7372e-04
Epoch 32/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5.7345e-04 - val_loss: 6.5403e-04
Epoch 33/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.9301e-04 - val_loss: 2.4833e-04
Epoch 34/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.4652e-04 - val_loss: 4.8252e-04
Epoch 35/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.5751e-04 - val_loss: 2.8891e-04
Epoch 36/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.0554e-04 - val_loss: 1.4652e-04
Epoch 37/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.8239e-04 - val_loss: 2.1293e-04
Epoch 38/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.2453e-04 - val_loss: 2.0707e-04
Epoch 39/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.9950e-04 - val_loss: 2.2085e-04
Epoch 40/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.9384e-04 - val_loss: 1.0661e-04
Epoch 41/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.5799e-04 - val_loss: 2.5824e-04
Epoch 42/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.4720e-04 - val_loss: 1.9648e-04
Epoch 43/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.4908e-04 - val_loss: 1.4286e-04
Epoch 44/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.4480e-04 - val_loss: 1.1058e-04
Epoch 45/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.2070e-04 - val_loss: 1.6433e-04
Epoch 46/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1032e-04 - val_loss: 1.7228e-04
Epoch 47/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.0642e-04 - val_loss: 1.7908e-04
Epoch 48/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.0936e-04 - val_loss: 1.9883e-04
Epoch 49/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.6789e-05 - val_loss: 2.0295e-04
Epoch 50/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0317e-04 - val_loss: 1.8134e-04
Epoch 51/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.9725e-05 - val_loss: 1.5821e-04
Epoch 52/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.1868e-05 - val_loss: 2.0307e-04
Epoch 53/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.5829e-05 - val_loss: 1.5199e-04
Epoch 54/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.3144e-05 - val_loss: 1.6084e-04
Epoch 55/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.3285e-05 - val_loss: 2.5366e-04
Epoch 56/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.1253e-05 - val_loss: 2.2721e-04
Epoch 57/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.9396e-05 - val_loss: 2.0583e-04
Epoch 58/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.6785e-05 - val_loss: 1.5736e-04
Epoch 59/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.3468e-05 - val_loss: 1.8877e-04
Epoch 60/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.8521e-05 - val_loss: 1.5290e-04
Epoch 61/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.2161e-04 - val_loss: 1.8054e-04
Epoch 62/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 8.1200e-05 - val_loss: 2.4032e-04
Epoch 63/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.1070e-05 - val_loss: 1.9363e-04
Epoch 64/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5584e-05 - val_loss: 1.3408e-04
Epoch 65/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.8252e-05 - val_loss: 1.1675e-04
Epoch 66/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.9269e-05 - val_loss: 1.0784e-04
Epoch 67/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.4220e-05 - val_loss: 1.1693e-04
Epoch 68/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.1115e-05 - val_loss: 1.2978e-04
Epoch 69/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.6389e-05 - val_loss: 1.1010e-04
Epoch 70/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 6.1102e-05 - val_loss: 1.8570e-04
Epoch 71/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.9406e-05 - val_loss: 1.7896e-04
Epoch 72/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.6109e-05 - val_loss: 9.7134e-05
Epoch 73/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.7950e-05 - val_loss: 1.5228e-04
Epoch 74/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5.0199e-05 - val_loss: 1.0585e-04
Epoch 75/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.9810e-05 - val_loss: 1.2606e-04
Epoch 76/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.9816e-05 - val_loss: 1.1360e-04
Epoch 77/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.8002e-05 - val_loss: 8.4781e-05
Epoch 78/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.9947e-05 - val_loss: 7.4956e-05
Epoch 79/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.3978e-05 - val_loss: 9.1254e-05
Epoch 80/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.2230e-05 - val_loss: 8.1258e-05
Epoch 81/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.0665e-05 - val_loss: 9.6990e-05
Epoch 82/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.9013e-05 - val_loss: 1.2785e-04
Epoch 83/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.2351e-05 - val_loss: 6.8484e-05
Epoch 84/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.5594e-05 - val_loss: 7.2747e-05
Epoch 85/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.9807e-05 - val_loss: 5.9555e-05
Epoch 86/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.3647e-05 - val_loss: 6.1370e-05
Epoch 87/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3.3130e-05 - val_loss: 6.9515e-05
Epoch 88/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.4074e-05 - val_loss: 5.6401e-05
Epoch 89/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 3.1649e-05 - val_loss: 6.1764e-05
Epoch 90/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.8853e-05 - val_loss: 5.6120e-05
Epoch 91/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3.0895e-05 - val_loss: 4.3616e-05
Epoch 92/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 3.0891e-05 - val_loss: 3.9461e-05
Epoch 93/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3.1100e-05 - val_loss: 4.3701e-05
Epoch 94/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2.5147e-05 - val_loss: 4.1945e-05
Epoch 95/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2.4725e-05 - val_loss: 3.7393e-05
Epoch 96/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2.4335e-05 - val_loss: 7.2355e-05
Epoch 97/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.1152e-05 - val_loss: 4.6223e-05
Epoch 98/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2.1447e-05 - val_loss: 4.6332e-05
Epoch 99/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.5294e-05 - val_loss: 3.8064e-05
Epoch 100/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.0304e-05 - val_loss: 3.3591e-05

In [120]:
Y_show=model.predict(X_train)

WARNING:tensorflow:5 out of the last 20 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x79e7a8118540> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step

# Result

In [121]:
Y_train_actual = scaler.inverse_transform(Y_train)
Y_show_actual = scaler.inverse_transform(Y_show)

rmse = np.sqrt(mean_squared_error(Y_train_actual, Y_show_actual))
print(f"Root Mean Squared Error (RMSE): {rmse}")

Root Mean Squared Error (RMSE): 0.2146730233105747

In [122]:
fig=go.Figure()
fig.add_trace(go.Scatter(x=[i for i in range(len(Y_train.T[0]))],y=scaler.inverse_transform(Y_train).T[0],name='Actual'))
fig.add_trace(go.Scatter(x=[i for i in range(len(Y_train.T[0]))],y=scaler.inverse_transform(Y_show).T[0],name='Predicted'))
fig.show()